### ISSUE TITLE
module 'zedbd' not found

### ISSUE THREAD

**Issue by wsong83** [furkanturan/lowrisc-zed#2]
Hello Furkan,

I try to follow your instructions to run the Zedboard demo, after I trying `make hello` (the first time to synthesize the project), Vivdao complains about module 'zedbd' not found in Wrapper.v

It does not seems like a library component. Am I miss some steps or maybe there is indeed lack of source files?

**Comment by furkanturan** [comment]
Hello Wei,

Sorry for the problem. It is happened probably because we use different versions. I am using Vivado 2016.2, and which version do you use?

zedbd is the block design I created in Vivado and exported as a tcl file. You can find it in scripts folder. When sourced, it should create the block design named zedbd. You can check the block design by opening the GUI with `make project` and then`make vivado`.

I have access to old 2015.2 version as well, and created another zedbd.tcl for this old version. Then I replaced it with the existing zedbd.tcl file in a new branch named 2015. It should work now.

Now, I am worried about the programming with `make program`. As I explained in the tutorial, fpga design depends on ARM processing system. Therefore, the program.tcl script initialises ps7 by executing predefined ps7_init.tcl on xsdk in batch mode. This is the method I used first time in this project, and I don't know if there is a difference in xsdk functionality between the two versions, but I will try to check it soon.

**Comment by wsong83** [comment]
I see. Currently I use 2015.4 and 2016.4 but I can install any version if needed. I hope the project should not be tied to a single version of Vivado. This feels a little bit odd for the error on my side. I will have a better look tomorrow. Thanks.

**Comment by wsong83** [comment]
It is caused by an unnecessary version check which can be removed. PR #3 tries to fix this issue.
