### ISSUE TITLE
Building a riscv rtos

### ISSUE THREAD

**Issue by ninode** [furkanturan/lowrisc-zed#9]
Hello Furkan,

Is it possible to push another small rtos with rocket cores to the fpga instead of linux ? As in by using Vivado to generate another boot.bin which contains another os than linux with the rocket chip ?

If it's possible, do you know what kind of files are necessary to do so ? 

Again, I couldn't thank you enough for your help.

Regards

**Comment by furkanturan** [comment]
Hello Ninode,

I was in a vacation and had limited internet access, so replying it late. I am sorry for this.

It is possible, but I have no experience on this. As far as I know the zephr OS is ported to RISC-V.

- [zephyrproject](https://www.zephyrproject.org)
- [https://github.com/fractalclone/zephyr-riscv](https://github.com/fractalclone/zephyr-riscv)
- [https://github.com/sergeykhbr/riscv_vhdl](https://github.com/sergeykhbr/riscv_vhdl)

These are some links to look at. There you should find the Zephyr OS files, and how to compile them. 

But don't forget that, at some point of it you should pass hardware information to the kernel. By hardware information, I mean the physical address of RAM, real-time clock, uart port, etc. Otherwise, the kernel cannot interface with the hardware.

In RISC-V, you can see in this [link](http://www.lowrisc.org/docs/debug-v0.3/soc_struct/) that, the device map is created for your configuration when your hardware is synthesised, and can be found as a string stored at the boot ROM. If Zephyr port is made to read this configuration from there, then it should be easy; otherwise, you may need to prepare a [Device Tree Source file](https://events.linuxfoundation.org/sites/events/files/slides/petazzoni-device-tree-dummies.pdf) and pass it to your kernel as a configuration file.

As I have no experience on this, I cannot give you exact steps to do this or talk about all the necessary files, but general structure should be as it is mentioned above.

Kind Regards,

Furkan

**Comment by ninode** [comment]
Thank you. 
How about running other binaries other than ones provided in /fpga/examples ?

**Comment by furkanturan** [comment]
Hello ninode,

The directory /fpga/examples should be for baremetal binaries if I don't remember it wrong. Those are compiled with the Makefiles (/zed/Makefile and /zed/examples/Makefile). So studying the Makefile structure, you can see how they are compiled. Then you can compile your files either with them, or individually.

If you talk about binaries executing on Linux, then similarly you can compile them with the riscv gcc toolchain that you should have installed while following the tutorial. Then you can load them into your SD card, boot Linux, [mount the SD card](http://www.lowrisc.org/docs/debug-v0.3/fpga/), and execute them there.

Regards,

Furkan

**Comment by ninode** [comment]
Yes, it's for binaries on the rocket core not on the arm linux.

> Then you can load them into your SD card, boot Linux, mount the SD card, and execute them there.

In this case will they be compiled but the rocket core or the arm ? 

Another question. Is it possible to toggle LEDs on the zedboard using a blinky program (also run on the rocket) ?

**Comment by furkanturan** [comment]
I think there is a confusion with ARM and Rocket Cores. In my port, ARM is completely idle. It only waits in an infinitely loop. The ARM is there, because physically it exists on the chip, and its memory controller is needed; therefore, but that does not mean we run a software on it, or Linux on it. Consider that it does not exist; or it is not a processor but just a piece of hardware.

Now, we have Rocket Core for RISC-V, and as many projects, you have two options. First, to run a baremetal software, which does not need an OS, runs on the core itself. The /fpga/bare_metal/examples/*.c are all examples to this. You can start with hello.c.

The second option is running OS on the core, and running you applications on the OS. You will run Linux on the Rocket Core, which is introduced in the tutorial. I did not (and also I don't expect from you to) install development tools on that Linux, but cross-compiled my code on the host machine, and transferred their executables to the zedboard using SD Card.

-----------
It is possible to run LEDs on a program, but please do not expect from me a detailed tutorial for that here. As a summary of what needs to be done for a simple design: you need to design a memory mapped AXI module, for example when you write data to a configuration register the LEDs will light up, when you clear it they will go off. Then, connect it to the design on the Vivado project; output pins to LEDs, and AXI port to one of RISC-V's ports, that needs selecting the port, and playing with Rocket Core generator input file, to make map your module to the core's address-space as well. Then again decide if you want bare-metal or Linux application. If bare-metal, just write your data to configuration register as you know the address of it since you will map it to the design. If Linux, you will do the same, but I assume you will need to access the address through using/writing a kernel module (e.g., device driver).

Regards,

Furkan
